### PR TITLE
Add support for MySQL replication

### PR DESCRIPTION
**Pull request by krallin**
This is still a work in progress, but I wanted to get it out there to have more eyes on it and discuss a few decision points.

This basically adds support for MySQL replication in a similar fashion to what https://github.com/aptible/docker-postgresql/pull/19 does for Postgres.

Here are a couple things that are worthy of note and perhaps discussion:

- This won't work as-is using existing databases. Specifically:
  - ~~Starting the DB will fail if there is no `server-id` file in `/var/db`. I think it's safe to default to 1 if there is no server ID is present.~~ Changed this, server ID now defaults to 1.
  - The remote root users will need to be altered and given `WITH GRANT OPTION` so that `--activate-leader` can be used to create a replication user. This *needs* to be done locally (i.e. e.g. `docker exec` or via mounting the data volume). We *could* get around this by requiring the master data volumes in `--activate-leader` and connecting over the local socket.
- I've opted to choose a random server ID for slaves. If the ID is already used, `--activate-leader` will fail. The server ID is in the range of 0-2^32-1, so the probability of a collision is (very) low. I think this strikes a good balance between robustness and ease of implementation.
- Running `--initialize-follower` **will lock the databases on the master for the duration of the backup**, effectively placing the master in read-only mode. We could get around this by using the `--single-transaction` option in `mysqdump`. There are however a few gotchas:
  - First, the backup may not be consistent if DDL operations (e.g. `ALTER TABLE`) are running on the DB at the same time (!). [This post has an example](https://www.percona.com/blog/2012/03/23/best-kept-mysqldump-secret/)
  - Second, it doesn't really work with MyISAM tables. I think we default to InnoDB, but I'm pretty sure we don't *disable* MyISAM, and so it might be in use if e.g. someone restored a backup from somewhere else in their Aptible DB.

And a couple FYIs:

- I still need to double-check that restarting an old data volume using this new image will enable binary logging (I'm pretty sure it does, but I'll check).
- ~~There's a bit of cleanup to do. I'll get this all down to just 3 environment variables passed from `--activate-leader` to `--initialize-follower. I'll probably rewrite `parse_url` in a similar fashion to what I did in https://github.com/aptible/docker-mongodb/pull/12 while I'm at it doing cleanup.~~ Done.
- Leader data volumes aren't needed to run `--activate-leader`. Just the master DB URL.
- This does use (and enforce) SSL, but without cert verification.

I still have to write bats tests. I do have a test suite ready right now that runs externally, but not internally to a container (it's a bit tricky to write a bats test considering all the stupid MySQL defaults that need to be entangled...). Here's what I have right now:

```
#!/bin/bash
set -o errexit
set -o nounset
set -o xtrace

space () {
  echo
  echo
  echo
  echo
  echo
  echo
  echo
  echo
}
IMG="quay.io/aptible/mysql:5.6"

DATA="/tmp/docker-mysql/data2"
MASTER_CONTAINER="master2"
SLAVE_CONTAINER="slave2"

# Cleanup
docker rm -f "$MASTER_CONTAINER" "$SLAVE_CONTAINER" || true
docker-machine ssh docker-vm sudo rm -rf "${DATA}"

make build

USER=testuser
PASSPHRASE=testpass
DATABASE=testdb

space
echo "Initializing master"
docker run -it --rm -e USERNAME="${USER}" -e PASSPHRASE="$PASSPHRASE" -e DATABASE="$DATABASE" -v "${DATA}/master:/var/db" "$IMG" --initialize

space
echo "Starting master"
MASTER_PORT=33061  # Test with a nonstandard port
docker run -d --name="$MASTER_CONTAINER" \
  -e "PORT=${MASTER_PORT}" \
  -v "${DATA}/master:/var/db" \
  "$IMG"

until docker exec -it "$MASTER_CONTAINER" mysqladmin ping; do sleep 0.1; done
docker logs "$MASTER_CONTAINER"

MASTER_IP="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$MASTER_CONTAINER")"

MASTER_USER_URL="mysql://$USER:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"
MASTER_ROOT_URL="mysql://root:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"

# Create a test table before replication starts
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "CREATE TABLE test_before (col TEXT);"
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "INSERT INTO test_before VALUES ('TEST DATA');"

space
echo "Activating leader"
eval "$(docker run -it --rm "$IMG" --activate-leader "$MASTER_ROOT_URL" | dos2unix)"


space
echo "Initializing slave"
echo "ID:        $MYSQL_REPLICATION_SLAVE_SERVER_ID"
echo "Root Url:  $MYSQL_REPLICATION_MASTER_ROOT_URL"
echo "Slave Url: $MYSQL_REPLICATION_MASTER_REPL_URL"


docker run -it --rm \
  -e "MYSQL_REPLICATION_SLAVE_SERVER_ID=$MYSQL_REPLICATION_SLAVE_SERVER_ID" \
  -e "MYSQL_REPLICATION_MASTER_ROOT_URL=$MYSQL_REPLICATION_MASTER_ROOT_URL" \
  -e "MYSQL_REPLICATION_MASTER_REPL_URL=$MYSQL_REPLICATION_MASTER_REPL_URL" \
  -v "${DATA}/slave:/var/db" \
  "$IMG" --initialize-follower

SLAVE_PORT=33062
docker run -d --name "$SLAVE_CONTAINER" \
  -e "PORT=${SLAVE_PORT}" \
  -v "${DATA}/slave:/var/db" \
  "$IMG"


SLAVE_IP="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$SLAVE_CONTAINER")"

SLAVE_ROOT_URL="mysql://root:$PASSPHRASE@$SLAVE_IP:$SLAVE_PORT/$DATABASE"
SLAVE_USER_URL="mysql://$USER:$PASSPHRASE@$SLAVE_IP:$SLAVE_PORT/$DATABASE"  


until docker exec -it "$SLAVE_CONTAINER" mysqladmin ping; do sleep 0.1; done
docker run -it --rm "$IMG" --client "$SLAVE_ROOT_URL" -e "SHOW SLAVE STATUS \G"

# Create a test table now that replication has started
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "CREATE TABLE test_after (col TEXT);"
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "INSERT INTO test_after VALUES ('TEST DATA');"

# Give replication time it needs to catch up (should usually be essentially instantaneous, but who knows,
# some CI systems might run slower.
until docker run --rm "$IMG" --client "$SLAVE_ROOT_URL" -e "SHOW SLAVE STATUS \G" | grep "Waiting for master to send event"; do sleep 0.1; done

# Check that data is present in both tables
docker run -it --rm "$IMG" --client "$SLAVE_USER_URL" -e 'SELECT * FROM test_before;' | grep 'TEST DATA'
docker run -it --rm "$IMG" --client "$SLAVE_USER_URL" -e 'SELECT * FROM test_after;' | grep 'TEST DATA'

echo "Test OK!"
```

Cheers,

### CODE REVIEW

**Comment by krallin** [comment]
@fancyremarker This should be essentially ready at this point, and I'm wondering what to do regarding tests:

- We could convert the test script to a BATS test. It's some work, but it's doable. However, it also doesn't perfectly reflect our architecture.
- We could reuse the test script, which runs outside of the container (and even convert it to bats tests if we want to). It would *not* run as part of a Docker build, but if we were to use Travis as CI to build our `docker-mysql` images, would that be a problem..?

Cheers,

**Comment by krallin** [comment]
@fancyremarker @aaw,

This one should be ready for review as well. It uses the same `--initialize-from` API we discussed in Slack and used in https://github.com/aptible/docker-redis/pull/10.

We might still need to chat about `--single-transaction`. Let me know if you'd like.

just like in https://github.com/aptible/docker-redis/pull/10, there will be a couple of Travis tweaks to do before merging.

Cheers,

**Comment by krallin** [comment]
Note, I have tested that we can upgrade existing DBs that didn't have binary logging initially enabled by slightly altering the test script to use the old DB image and running it (`quay.io/aptible/mysql:5.6` was `2c231a66587190db4c0118eb2a4f02b861667a4bc6af4a6481bd3e70821e8496`):

```
#!/bin/bash
set -o errexit
set -o nounset
set -o xtrace


IMG="$REGISTRY/$REPOSITORY:$TAG"

MASTER_CONTAINER="mysql-master"
MASTER_DATA_CONTAINER="${MASTER_CONTAINER}-data"
SLAVE_CONTAINER="mysql-slave"
SLAVE_DATA_CONTAINER="${SLAVE_CONTAINER}-data"

function cleanup {
  echo "Cleaning up"
  docker rm -f "$MASTER_CONTAINER" "$MASTER_DATA_CONTAINER" "$SLAVE_CONTAINER" "$SLAVE_DATA_CONTAINER" || true
}

trap cleanup EXIT
cleanup

USER=testuser
PASSPHRASE=testpass
DATABASE=testdb


echo "Initializing data containers"

docker create --name "$MASTER_DATA_CONTAINER" "$IMG"
docker create --name "$SLAVE_DATA_CONTAINER" "$IMG"


echo "Initializing replication master"

MASTER_PORT=3306  # Test with a nonstandard port


OLD_IMG="quay.io/aptible/mysql:5.6"

docker run -it --rm \
  -e USERNAME="$USER" -e PASSPHRASE="$PASSPHRASE" -e DATABASE="$DATABASE" \
  --volumes-from "$MASTER_DATA_CONTAINER" \
  "$OLD_IMG" --initialize

docker run -d --name="$MASTER_CONTAINER" \
  --volumes-from "$MASTER_DATA_CONTAINER" \
  "$OLD_IMG"


until docker exec -it "$MASTER_CONTAINER" mysqladmin ping; do sleep 0.1; done

MASTER_IP="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$MASTER_CONTAINER")"
MASTER_USER_URL="mysql://$USER:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"
MASTER_ROOT_URL="mysql://root:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"


echo "Creating test_before table"

docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "CREATE TABLE test_before (col TEXT);"
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "INSERT INTO test_before VALUES ('TEST DATA BEFORE');"


# Upgrade to new image

docker exec -it "$MASTER_CONTAINER" mysql -e "GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;"

docker kill "$MASTER_CONTAINER"
docker rm "$MASTER_CONTAINER"

docker run -d --name="$MASTER_CONTAINER" \
  --volumes-from "$MASTER_DATA_CONTAINER" \
  "$IMG"

until docker exec -it "$MASTER_CONTAINER" mysqladmin ping; do sleep 0.1; done

MASTER_IP="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$MASTER_CONTAINER")"
MASTER_USER_URL="mysql://$USER:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"
MASTER_ROOT_URL="mysql://root:$PASSPHRASE@$MASTER_IP:$MASTER_PORT/$DATABASE"


echo "Initializing replication slave"
SLAVE_PORT=33062

docker run -it --rm \
  --volumes-from "$SLAVE_DATA_CONTAINER" \
  "$IMG" --initialize-from "$MASTER_USER_URL"   # Use the user URL, but --initialize-from will use root instead

docker run -d --name "$SLAVE_CONTAINER" \
  -e "PORT=${SLAVE_PORT}" \
  --volumes-from "$SLAVE_DATA_CONTAINER" \
  "$IMG"


SLAVE_IP="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' "$SLAVE_CONTAINER")"
SLAVE_ROOT_URL="mysql://root:$PASSPHRASE@$SLAVE_IP:$SLAVE_PORT/$DATABASE"
SLAVE_USER_URL="mysql://$USER:$PASSPHRASE@$SLAVE_IP:$SLAVE_PORT/$DATABASE"


until docker exec -it "$SLAVE_CONTAINER" mysqladmin ping; do sleep 0.1; done
docker run -it --rm "$IMG" --client "$SLAVE_ROOT_URL" -e "SHOW SLAVE STATUS \G"


# Create a test table now that replication has started
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "CREATE TABLE test_after (col TEXT);"
docker run -it --rm "$IMG" --client "$MASTER_USER_URL" -e "INSERT INTO test_after VALUES ('TEST DATA AFTER');"

# Give replication time it needs to catch up (should usually be essentially instantaneous, but who knows,
# some CI systems might run slower.
until docker run --rm "$IMG" --client "$SLAVE_ROOT_URL" -e "SHOW SLAVE STATUS \G" | grep "Waiting for master to send event"; do sleep 0.1; done

# Check that data is present in both tables
docker run -it --rm "$IMG" --client "$SLAVE_USER_URL" -e 'SELECT * FROM test_before;' | grep 'TEST DATA BEFORE'
docker run -it --rm "$IMG" --client "$SLAVE_USER_URL" -e 'SELECT * FROM test_after;' | grep 'TEST DATA AFTER'

echo "Test OK!"

```


Also, note that this PR will resolve #10 for new databases. I'm unclear about #14 though — even in the current image, it appears root does have the `SUPER` privilege (it's missing the `GRANT` privilege though, but this one we're adding here):

```
mysql> SELECT * FROM mysql.user WHERE user = 'root' \G
*************************** 1. row ***************************
                  Host: localhost
                  User: root
              Password: 
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: Y
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: 
      password_expired: N
*************************** 2. row ***************************
                  Host: b4d76afaec2f
                  User: root
              Password: 
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: Y
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: 
      password_expired: N
*************************** 3. row ***************************
                  Host: 127.0.0.1
                  User: root
              Password: 
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: Y
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: 
      password_expired: N
*************************** 4. row ***************************
                  Host: ::1
                  User: root
              Password: 
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: Y
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: 
      password_expired: N
*************************** 5. row ***************************
                  Host: %
                  User: root
              Password: 
           Select_priv: Y
           Insert_priv: Y
           Update_priv: Y
           Delete_priv: Y
           Create_priv: Y
             Drop_priv: Y
           Reload_priv: Y
         Shutdown_priv: Y
          Process_priv: Y
             File_priv: Y
            Grant_priv: N
       References_priv: Y
            Index_priv: Y
            Alter_priv: Y
          Show_db_priv: Y
            Super_priv: Y
 Create_tmp_table_priv: Y
      Lock_tables_priv: Y
          Execute_priv: Y
       Repl_slave_priv: Y
      Repl_client_priv: Y
      Create_view_priv: Y
        Show_view_priv: Y
   Create_routine_priv: Y
    Alter_routine_priv: Y
      Create_user_priv: Y
            Event_priv: Y
          Trigger_priv: Y
Create_tablespace_priv: Y
              ssl_type: 
            ssl_cipher: 
           x509_issuer: 
          x509_subject: 
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: 
      password_expired: N
5 rows in set (0.00 sec)
```

**Comment by fancyremarker** [comment]
This looks great to me! I'm continuing to review the others but I think this API is good to move forward with.

**Comment by silasb** [comment]
Looks like Oracle bumped MySQL to `5.6.29-1debian7` from `5.6.28-1debian7`.

I also think that we need to remove `mysql-client` since the server package now includes a client already.

**Comment by krallin** [comment]
Thanks for your feedback @silasb,

I'm not sure I'm following your suggestion to remove `mysql-client`. It looks like some of the tools we use (e.g. `mysqldump`) are coming from that package:

```
root@c88bf0e1b252:/# apt-get install mysql-server=5.6.29-1debian7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  mysql-client mysql-common mysql-community-client mysql-community-server
The following packages will be upgraded:
  mysql-client mysql-common mysql-community-client mysql-community-server mysql-server
5 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
Need to get 50.5 MB of archives.
After this operation, 57.3 kB disk space will be freed.
Do you want to continue [Y/n]? y
Get:1 http://repo.mysql.com/apt/debian/ wheezy/mysql-5.6 mysql-client amd64 5.6.29-1debian7 [11.7 kB]
Get:2 http://repo.mysql.com/apt/debian/ wheezy/mysql-5.6 mysql-community-client amd64 5.6.29-1debian7 [21.8 MB]
Get:3 http://repo.mysql.com/apt/debian/ wheezy/mysql-5.6 mysql-server amd64 5.6.29-1debian7 [11.7 kB]
Get:4 http://repo.mysql.com/apt/debian/ wheezy/mysql-5.6 mysql-community-server amd64 5.6.29-1debian7 [28.0 MB]
Get:5 http://repo.mysql.com/apt/debian/ wheezy/mysql-5.6 mysql-common amd64 5.6.29-1debian7 [700 kB]                                   
Fetched 50.5 MB in 11s (4341 kB/s)                                                                                                     
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 10734 files and directories currently installed.)
Preparing to replace mysql-client 5.6.28-1debian7 (using .../mysql-client_5.6.29-1debian7_amd64.deb) ...
Unpacking replacement mysql-client ...
Preparing to replace mysql-community-client 5.6.28-1debian7 (using .../mysql-community-client_5.6.29-1debian7_amd64.deb) ...
Unpacking replacement mysql-community-client ...
Preparing to replace mysql-server 5.6.28-1debian7 (using .../mysql-server_5.6.29-1debian7_amd64.deb) ...
Unpacking replacement mysql-server ...
Preparing to replace mysql-community-server 5.6.28-1debian7 (using .../mysql-community-server_5.6.29-1debian7_amd64.deb) ...
invoke-rc.d: policy-rc.d denied execution of stop.
.
Unpacking replacement mysql-community-server ...
Preparing to replace mysql-common 5.6.28-1debian7 (using .../mysql-common_5.6.29-1debian7_amd64.deb) ...
Unpacking replacement mysql-common ...
Setting up mysql-common (5.6.29-1debian7) ...
Setting up mysql-community-client (5.6.29-1debian7) ...
Setting up mysql-client (5.6.29-1debian7) ...
Setting up mysql-community-server (5.6.29-1debian7) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
invoke-rc.d: policy-rc.d denied execution of start.
Setting up mysql-server (5.6.29-1debian7) ...

root@c88bf0e1b252:/# dpkg -L mysql-community-client
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/mysql-community-client
/usr/share/doc/mysql-community-client/COPYING.gz
/usr/share/doc/mysql-community-client/copyright
/usr/share/doc/mysql-community-client/changelog.Debian.gz
/usr/share/doc/mysql-community-client/README
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/mysql-community-client
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/mysql_waitpid.1.gz
/usr/share/man/man1/mysql_fix_extensions.1.gz
/usr/share/man/man1/mysqlcheck.1.gz
/usr/share/man/man1/mysqlbug.1.gz
/usr/share/man/man1/mysql_plugin.1.gz
/usr/share/man/man1/mysql_client_test_embedded.1.gz
/usr/share/man/man1/mysql.1.gz
/usr/share/man/man1/mysqlimport.1.gz
/usr/share/man/man1/innochecksum.1.gz
/usr/share/man/man1/myisam_ftdump.1.gz
/usr/share/man/man1/mysql_client_test.1.gz
/usr/share/man/man1/mysqldump.1.gz
/usr/share/man/man1/mysqlslap.1.gz
/usr/share/man/man1/mysqladmin.1.gz
/usr/share/man/man1/mysqldumpslow.1.gz
/usr/share/man/man1/mysqlman.1.gz
/usr/share/man/man1/mysqlaccess.1.gz
/usr/share/man/man1/mysqlshow.1.gz
/usr/share/man/man1/mysql_find_rows.1.gz
/usr/bin
/usr/bin/mysqlimport
/usr/bin/mysqldump
/usr/bin/mysql_waitpid
/usr/bin/mysql_embedded
/usr/bin/mysqlaccess.conf
/usr/bin/mysqladmin
/usr/bin/mysql_plugin
/usr/bin/mysqlslap
/usr/bin/mysql_client_test_embedded
/usr/bin/mysqlbug
/usr/bin/mysqlaccess
/usr/bin/mysql_find_rows
/usr/bin/myisam_ftdump
/usr/bin/mysqldumpslow
/usr/bin/mysql_client_test
/usr/bin/mysqlshow
/usr/bin/mysql_fix_extensions
/usr/bin/mysqlcheck
/usr/bin/innochecksum
/usr/bin/mysql
/usr/share/man/man1/mysql_embedded.1.gz


root@c88bf0e1b252:/# dpkg -L mysql-community-server
/.
/etc
/etc/init.d
/etc/init.d/mysql
/etc/mysql
/etc/mysql/conf.d
/usr
/usr/lib
/usr/lib/mysql
/usr/lib/mysql/plugin
/usr/lib/mysql/plugin/libdaemon_example.so
/usr/lib/mysql/plugin/mysql_no_login.so
/usr/lib/mysql/plugin/innodb_engine.so
/usr/lib/mysql/plugin/validate_password.so
/usr/lib/mysql/plugin/qa_auth_interface.so
/usr/lib/mysql/plugin/semisync_slave.so
/usr/lib/mysql/plugin/libmemcached.so
/usr/lib/mysql/plugin/auth.so
/usr/lib/mysql/plugin/semisync_master.so
/usr/lib/mysql/plugin/auth_socket.so
/usr/lib/mysql/plugin/daemon_example.ini
/usr/lib/mysql/plugin/debug
/usr/lib/mysql/plugin/debug/libdaemon_example.so
/usr/lib/mysql/plugin/debug/mysql_no_login.so
/usr/lib/mysql/plugin/debug/innodb_engine.so
/usr/lib/mysql/plugin/debug/validate_password.so
/usr/lib/mysql/plugin/debug/qa_auth_interface.so
/usr/lib/mysql/plugin/debug/semisync_slave.so
/usr/lib/mysql/plugin/debug/libmemcached.so
/usr/lib/mysql/plugin/debug/auth.so
/usr/lib/mysql/plugin/debug/semisync_master.so
/usr/lib/mysql/plugin/debug/auth_socket.so
/usr/lib/mysql/plugin/debug/daemon_example.ini
/usr/lib/mysql/plugin/debug/mypluglib.so
/usr/lib/mysql/plugin/debug/qa_auth_server.so
/usr/lib/mysql/plugin/debug/auth_test_plugin.so
/usr/lib/mysql/plugin/debug/qa_auth_client.so
/usr/lib/mysql/plugin/debug/adt_null.so
/usr/lib/mysql/plugin/mypluglib.so
/usr/lib/mysql/plugin/qa_auth_server.so
/usr/lib/mysql/plugin/auth_test_plugin.so
/usr/lib/mysql/plugin/qa_auth_client.so
/usr/lib/mysql/plugin/adt_null.so
/usr/sbin
/usr/sbin/mysqld-debug
/usr/sbin/mysqld
/usr/share
/usr/share/doc
/usr/share/doc/mysql-community-server
/usr/share/doc/mysql-community-server/COPYING.gz
/usr/share/doc/mysql-community-server/copyright
/usr/share/doc/mysql-community-server/changelog.Debian.gz
/usr/share/doc/mysql-community-server/README
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/mysql-community-server
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/mysqld.8.gz
/usr/share/man/man1
/usr/share/man/man1/mysqlbinlog.1.gz
/usr/share/man/man1/my_print_defaults.1.gz
/usr/share/man/man1/myisamchk.1.gz
/usr/share/man/man1/mysqltest.1.gz
/usr/share/man/man1/msql2mysql.1.gz
/usr/share/man/man1/mysql_tzinfo_to_sql.1.gz
/usr/share/man/man1/perror.1.gz
/usr/share/man/man1/resolveip.1.gz
/usr/share/man/man1/mysql_convert_table_format.1.gz
/usr/share/man/man1/mysql_upgrade.1.gz
/usr/share/man/man1/mysql_zap.1.gz
/usr/share/man/man1/mysql_setpermission.1.gz
/usr/share/man/man1/mysql.server.1.gz
/usr/share/man/man1/myisampack.1.gz
/usr/share/man/man1/myisamlog.1.gz
/usr/share/man/man1/mysql_secure_installation.1.gz
/usr/share/man/man1/mysqlhotcopy.1.gz
/usr/share/man/man1/mysql_install_db.1.gz
/usr/share/man/man1/resolve_stack_dump.1.gz
/usr/share/man/man1/mysqltest_embedded.1.gz
/usr/share/man/man1/mysqld_multi.1.gz
/usr/share/man/man1/replace.1.gz
/usr/share/man/man1/mysqld_safe.1.gz
/usr/share/man/man1/comp_err.1.gz
/usr/share/man/man1/mysql-stress-test.pl.1.gz
/usr/share/mysql
/usr/share/mysql/mysql_security_commands.sql
/usr/share/mysql/mysqld_multi.server
/usr/share/mysql/mysql_system_tables_data.sql
/usr/share/mysql/dictionary.txt
/usr/share/mysql/mysql-log-rotate
/usr/share/mysql/my-default.cnf
/usr/share/mysql/magic
/usr/share/mysql/innodb_memcached_config.sql
/usr/share/mysql/mysql_test_data_timezone.sql
/usr/share/mysql/fill_help_tables.sql
/usr/share/mysql/mysql_system_tables.sql
/usr/bin
/usr/bin/myisamchk
/usr/bin/myisampack
/usr/bin/mysqltest
/usr/bin/resolve_stack_dump
/usr/bin/mysql_convert_table_format
/usr/bin/perror
/usr/bin/myisamlog
/usr/bin/replace
/usr/bin/mysqltest_embedded
/usr/bin/my_print_defaults
/usr/bin/msql2mysql
/usr/bin/mysql_setpermission
/usr/bin/mysql_install_db
/usr/bin/mysqld_multi
/usr/bin/mysql_zap
/usr/bin/mysqld_safe
/usr/bin/mysqlbinlog
/usr/bin/mysql_secure_installation
/usr/bin/resolveip
/usr/bin/mysql_tzinfo_to_sql
/usr/bin/mysqlhotcopy
/usr/bin/mysql_upgrade
```

Or perhaps you meant that since `mysql-community-server` recommends `mysql-client`, we don't necessarily need to explicitly install the latter?

**Pull request merged**
